using System;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using System.Diagnostics;
using System.Reflection;
using System.Threading.Tasks;
using System.Collections.Generic;

using System.Text.RegularExpressions;
using Microsoft.Data.Analysis;

using DxMLEngine.Attributes;
using DxMLEngine.Functions;
using DxMLEngine.Objects;

namespace DxMLEngine.Features.GooglePatents
{
    internal class PatentCodePatterns
    {
        public const string WO_CODE = @"[W][O][\d\w]+";
        public const string US_CODE = @"[U][S][\d\w]+";
        public const string EP_CODE = @"[E][P][\d\w]+";
        public const string JP_CODE = @"[J][P][\d\w]+";
        public const string KR_CODE = @"[K][R][\d\w]+";
        public const string CN_CODE = @"[C][N][\d\w]+";
        public const string AE_CODE = @"[A][E][\d\w]+";
        public const string AG_CODE = @"[A][G][\d\w]+";
        public const string AL_CODE = @"[A][L][\d\w]+";
        public const string AM_CODE = @"[A][M][\d\w]+";
        public const string AO_CODE = @"[A][O][\d\w]+";
        public const string AP_CODE = @"[A][P][\d\w]+";
        public const string AR_CODE = @"[A][R][\d\w]+";
        public const string AT_CODE = @"[A][T][\d\w]+";
        public const string AU_CODE = @"[A][U][\d\w]+";
        public const string AW_CODE = @"[A][W][\d\w]+";
        public const string AZ_CODE = @"[A][Z][\d\w]+";
        public const string BA_CODE = @"[B][A][\d\w]+";
        public const string BB_CODE = @"[B][B][\d\w]+";
        public const string BD_CODE = @"[B][D][\d\w]+";
        public const string BE_CODE = @"[B][E][\d\w]+";
        public const string BF_CODE = @"[B][F][\d\w]+";
        public const string BG_CODE = @"[B][G][\d\w]+";
        public const string BH_CODE = @"[B][H][\d\w]+";
        public const string BJ_CODE = @"[B][J][\d\w]+";
        public const string BN_CODE = @"[B][N][\d\w]+";
        public const string BO_CODE = @"[B][O][\d\w]+";
        public const string BR_CODE = @"[B][R][\d\w]+";
        public const string BW_CODE = @"[B][W][\d\w]+";
        public const string BX_CODE = @"[B][X][\d\w]+";
        public const string BY_CODE = @"[B][Y][\d\w]+";
        public const string BZ_CODE = @"[B][Z][\d\w]+";
        public const string CA_CODE = @"[C][A][\d\w]+";
        public const string CF_CODE = @"[C][F][\d\w]+";
        public const string CG_CODE = @"[C][G][\d\w]+";
        public const string CH_CODE = @"[C][H][\d\w]+";
        public const string CI_CODE = @"[C][I][\d\w]+";
        public const string CL_CODE = @"[C][L][\d\w]+";
        public const string CM_CODE = @"[C][M][\d\w]+";
        public const string CO_CODE = @"[C][O][\d\w]+";
        public const string CR_CODE = @"[C][R][\d\w]+";
        public const string CS_CODE = @"[C][S][\d\w]+";
        public const string CU_CODE = @"[C][U][\d\w]+";
        public const string CY_CODE = @"[C][Y][\d\w]+";
        public const string CZ_CODE = @"[C][Z][\d\w]+";
        public const string DD_CODE = @"[D][D][\d\w]+";
        public const string DE_CODE = @"[D][E][\d\w]+";
        public const string DJ_CODE = @"[D][J][\d\w]+";
        public const string DK_CODE = @"[D][K][\d\w]+";
        public const string DM_CODE = @"[D][M][\d\w]+";
        public const string DO_CODE = @"[D][O][\d\w]+";
        public const string DZ_CODE = @"[D][Z][\d\w]+";
        public const string EA_CODE = @"[E][A][\d\w]+";
        public const string EC_CODE = @"[E][C][\d\w]+";
        public const string EE_CODE = @"[E][E][\d\w]+";
        public const string EG_CODE = @"[E][G][\d\w]+";
        public const string EM_CODE = @"[E][M][\d\w]+";
        public const string ES_CODE = @"[E][S][\d\w]+";
        public const string FI_CODE = @"[F][I][\d\w]+";
        public const string FR_CODE = @"[F][R][\d\w]+";
        public const string GA_CODE = @"[G][A][\d\w]+";
        public const string GB_CODE = @"[G][B][\d\w]+";
        public const string GC_CODE = @"[G][C][\d\w]+";
        public const string GD_CODE = @"[G][D][\d\w]+";
        public const string GE_CODE = @"[G][E][\d\w]+";
        public const string GH_CODE = @"[G][H][\d\w]+";
        public const string GM_CODE = @"[G][M][\d\w]+";
        public const string GN_CODE = @"[G][N][\d\w]+";
        public const string GQ_CODE = @"[G][Q][\d\w]+";
        public const string GR_CODE = @"[G][R][\d\w]+";
        public const string GT_CODE = @"[G][T][\d\w]+";
        public const string GW_CODE = @"[G][W][\d\w]+";
        public const string HK_CODE = @"[H][K][\d\w]+";
        public const string HN_CODE = @"[H][N][\d\w]+";
        public const string HR_CODE = @"[H][R][\d\w]+";
        public const string HU_CODE = @"[H][U][\d\w]+";
        public const string IB_CODE = @"[I][B][\d\w]+";
        public const string ID_CODE = @"[I][D][\d\w]+";
        public const string IE_CODE = @"[I][E][\d\w]+";
        public const string IL_CODE = @"[I][L][\d\w]+";
        public const string IN_CODE = @"[I][N][\d\w]+";
        public const string IR_CODE = @"[I][R][\d\w]+";
        public const string IS_CODE = @"[I][S][\d\w]+";
        public const string IT_CODE = @"[I][T][\d\w]+";
        public const string JO_CODE = @"[J][O][\d\w]+";
        public const string KE_CODE = @"[K][E][\d\w]+";
        public const string KG_CODE = @"[K][G][\d\w]+";
        public const string KH_CODE = @"[K][H][\d\w]+";
        public const string KM_CODE = @"[K][M][\d\w]+";
        public const string KN_CODE = @"[K][N][\d\w]+";
        public const string KP_CODE = @"[K][P][\d\w]+";
        public const string KW_CODE = @"[K][W][\d\w]+";
        public const string KZ_CODE = @"[K][Z][\d\w]+";
        public const string LA_CODE = @"[L][A][\d\w]+";
        public const string LC_CODE = @"[L][C][\d\w]+";
        public const string LI_CODE = @"[L][I][\d\w]+";
        public const string LK_CODE = @"[L][K][\d\w]+";
        public const string LR_CODE = @"[L][R][\d\w]+";
        public const string LS_CODE = @"[L][S][\d\w]+";
        public const string LT_CODE = @"[L][T][\d\w]+";
        public const string LU_CODE = @"[L][U][\d\w]+";
        public const string LV_CODE = @"[L][V][\d\w]+";
        public const string LY_CODE = @"[L][Y][\d\w]+";
        public const string MA_CODE = @"[M][A][\d\w]+";
        public const string MC_CODE = @"[M][C][\d\w]+";
        public const string MD_CODE = @"[M][D][\d\w]+";
        public const string ME_CODE = @"[M][E][\d\w]+";
        public const string MG_CODE = @"[M][G][\d\w]+";
        public const string MK_CODE = @"[M][K][\d\w]+";
        public const string ML_CODE = @"[M][L][\d\w]+";
        public const string MN_CODE = @"[M][N][\d\w]+";
        public const string MO_CODE = @"[M][O][\d\w]+";
        public const string MR_CODE = @"[M][R][\d\w]+";
        public const string MT_CODE = @"[M][T][\d\w]+";
        public const string MW_CODE = @"[M][W][\d\w]+";
        public const string MX_CODE = @"[M][X][\d\w]+";
        public const string MY_CODE = @"[M][Y][\d\w]+";
        public const string MZ_CODE = @"[M][Z][\d\w]+";
        public const string NA_CODE = @"[N][A][\d\w]+";
        public const string NE_CODE = @"[N][E][\d\w]+";
        public const string NG_CODE = @"[N][G][\d\w]+";
        public const string NI_CODE = @"[N][I][\d\w]+";
        public const string NL_CODE = @"[N][L][\d\w]+";
        public const string NO_CODE = @"[N][O][\d\w]+";
        public const string NZ_CODE = @"[N][Z][\d\w]+";
        public const string OA_CODE = @"[O][A][\d\w]+";
        public const string OM_CODE = @"[O][M][\d\w]+";
        public const string PA_CODE = @"[P][A][\d\w]+";
        public const string PE_CODE = @"[P][E][\d\w]+";
        public const string PG_CODE = @"[P][G][\d\w]+";
        public const string PH_CODE = @"[P][H][\d\w]+";
        public const string PL_CODE = @"[P][L][\d\w]+";
        public const string PT_CODE = @"[P][T][\d\w]+";
        public const string PY_CODE = @"[P][Y][\d\w]+";
        public const string QA_CODE = @"[Q][A][\d\w]+";
        public const string RO_CODE = @"[R][O][\d\w]+";
        public const string RS_CODE = @"[R][S][\d\w]+";
        public const string RU_CODE = @"[R][U][\d\w]+";
        public const string RW_CODE = @"[R][W][\d\w]+";
        public const string SA_CODE = @"[S][A][\d\w]+";
        public const string SC_CODE = @"[S][C][\d\w]+";
        public const string SD_CODE = @"[S][D][\d\w]+";
        public const string SE_CODE = @"[S][E][\d\w]+";
        public const string SG_CODE = @"[S][G][\d\w]+";
        public const string SI_CODE = @"[S][I][\d\w]+";
        public const string SK_CODE = @"[S][K][\d\w]+";
        public const string SL_CODE = @"[S][L][\d\w]+";
        public const string SM_CODE = @"[S][M][\d\w]+";
        public const string SN_CODE = @"[S][N][\d\w]+";
        public const string ST_CODE = @"[S][T][\d\w]+";
        public const string SU_CODE = @"[S][U][\d\w]+";
        public const string SV_CODE = @"[S][V][\d\w]+";
        public const string SY_CODE = @"[S][Y][\d\w]+";
        public const string SZ_CODE = @"[S][Z][\d\w]+";
        public const string TD_CODE = @"[T][D][\d\w]+";
        public const string TG_CODE = @"[T][G][\d\w]+";
        public const string TH_CODE = @"[T][H][\d\w]+";
        public const string TJ_CODE = @"[T][J][\d\w]+";
        public const string TM_CODE = @"[T][M][\d\w]+";
        public const string TN_CODE = @"[T][N][\d\w]+";
        public const string TR_CODE = @"[T][R][\d\w]+";
        public const string TT_CODE = @"[T][T][\d\w]+";
        public const string TW_CODE = @"[T][W][\d\w]+";
        public const string TZ_CODE = @"[T][Z][\d\w]+";
        public const string UA_CODE = @"[U][A][\d\w]+";
        public const string UG_CODE = @"[U][G][\d\w]+";
        public const string UY_CODE = @"[U][Y][\d\w]+";
        public const string UZ_CODE = @"[U][Z][\d\w]+";
        public const string VC_CODE = @"[V][C][\d\w]+";
        public const string VE_CODE = @"[V][E][\d\w]+";
        public const string VN_CODE = @"[V][N][\d\w]+";
        public const string YU_CODE = @"[Y][U][\d\w]+";
        public const string ZA_CODE = @"[Z][A][\d\w]+";
        public const string ZM_CODE = @"[Z][M][\d\w]+";
        public const string ZW_CODE = @"[Z][W][\d\w]+";
    }
}
