using System;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using System.Diagnostics;
using System.Reflection;
using System.Threading.Tasks;
using System.Collections.Generic;

using System.Text.RegularExpressions;
using Microsoft.Data.Analysis;

using DxMLEngine.Attributes;
using DxMLEngine.Functions;
using DxMLEngine.Objects;

namespace DxMLEngine.Features.GooglePatents
{
    internal class PatentCodePatterns
    {
        public const string WO_CODE = @"[W][O][\d\w]+";
        public const string US_CODE = @"[U][S][\d\w]+";
        public const string EP_CODE = @"NotImplemented";
        public const string JP_CODE = @"NotImplemented";
        public const string KR_CODE = @"NotImplemented";
        public const string CN_CODE = @"NotImplemented";
        public const string AE_CODE = @"NotImplemented";
        public const string AG_CODE = @"NotImplemented";
        public const string AL_CODE = @"NotImplemented";
        public const string AM_CODE = @"NotImplemented";
        public const string AO_CODE = @"NotImplemented";
        public const string AP_CODE = @"NotImplemented";
        public const string AR_CODE = @"NotImplemented";
        public const string AT_CODE = @"NotImplemented";
        public const string AU_CODE = @"NotImplemented";
        public const string AW_CODE = @"NotImplemented";
        public const string AZ_CODE = @"NotImplemented";
        public const string BA_CODE = @"NotImplemented";
        public const string BB_CODE = @"NotImplemented";
        public const string BD_CODE = @"NotImplemented";
        public const string BE_CODE = @"NotImplemented";
        public const string BF_CODE = @"NotImplemented";
        public const string BG_CODE = @"NotImplemented";
        public const string BH_CODE = @"NotImplemented";
        public const string BJ_CODE = @"NotImplemented";
        public const string BN_CODE = @"NotImplemented";
        public const string BO_CODE = @"NotImplemented";
        public const string BR_CODE = @"NotImplemented";
        public const string BW_CODE = @"NotImplemented";
        public const string BX_CODE = @"NotImplemented";
        public const string BY_CODE = @"NotImplemented";
        public const string BZ_CODE = @"NotImplemented";
        public const string CA_CODE = @"NotImplemented";
        public const string CF_CODE = @"NotImplemented";
        public const string CG_CODE = @"NotImplemented";
        public const string CH_CODE = @"NotImplemented";
        public const string CI_CODE = @"NotImplemented";
        public const string CL_CODE = @"NotImplemented";
        public const string CM_CODE = @"NotImplemented";
        public const string CO_CODE = @"NotImplemented";
        public const string CR_CODE = @"NotImplemented";
        public const string CS_CODE = @"NotImplemented";
        public const string CU_CODE = @"NotImplemented";
        public const string CY_CODE = @"NotImplemented";
        public const string CZ_CODE = @"NotImplemented";
        public const string DD_CODE = @"NotImplemented";
        public const string DE_CODE = @"NotImplemented";
        public const string DJ_CODE = @"NotImplemented";
        public const string DK_CODE = @"NotImplemented";
        public const string DM_CODE = @"NotImplemented";
        public const string DO_CODE = @"NotImplemented";
        public const string DZ_CODE = @"NotImplemented";
        public const string EA_CODE = @"NotImplemented";
        public const string EC_CODE = @"NotImplemented";
        public const string EE_CODE = @"NotImplemented";
        public const string EG_CODE = @"NotImplemented";
        public const string EM_CODE = @"NotImplemented";
        public const string ES_CODE = @"NotImplemented";
        public const string FI_CODE = @"NotImplemented";
        public const string FR_CODE = @"NotImplemented";
        public const string GA_CODE = @"NotImplemented";
        public const string GB_CODE = @"NotImplemented";
        public const string GC_CODE = @"NotImplemented";
        public const string GD_CODE = @"NotImplemented";
        public const string GE_CODE = @"NotImplemented";
        public const string GH_CODE = @"NotImplemented";
        public const string GM_CODE = @"NotImplemented";
        public const string GN_CODE = @"NotImplemented";
        public const string GQ_CODE = @"NotImplemented";
        public const string GR_CODE = @"NotImplemented";
        public const string GT_CODE = @"NotImplemented";
        public const string GW_CODE = @"NotImplemented";
        public const string HK_CODE = @"NotImplemented";
        public const string HN_CODE = @"NotImplemented";
        public const string HR_CODE = @"NotImplemented";
        public const string HU_CODE = @"NotImplemented";
        public const string IB_CODE = @"NotImplemented";
        public const string ID_CODE = @"NotImplemented";
        public const string IE_CODE = @"NotImplemented";
        public const string IL_CODE = @"NotImplemented";
        public const string IN_CODE = @"NotImplemented";
        public const string IR_CODE = @"NotImplemented";
        public const string IS_CODE = @"NotImplemented";
        public const string IT_CODE = @"NotImplemented";
        public const string JO_CODE = @"NotImplemented";
        public const string KE_CODE = @"NotImplemented";
        public const string KG_CODE = @"NotImplemented";
        public const string KH_CODE = @"NotImplemented";
        public const string KM_CODE = @"NotImplemented";
        public const string KN_CODE = @"NotImplemented";
        public const string KP_CODE = @"NotImplemented";
        public const string KW_CODE = @"NotImplemented";
        public const string KZ_CODE = @"NotImplemented";
        public const string LA_CODE = @"NotImplemented";
        public const string LC_CODE = @"NotImplemented";
        public const string LI_CODE = @"NotImplemented";
        public const string LK_CODE = @"NotImplemented";
        public const string LR_CODE = @"NotImplemented";
        public const string LS_CODE = @"NotImplemented";
        public const string LT_CODE = @"NotImplemented";
        public const string LU_CODE = @"NotImplemented";
        public const string LV_CODE = @"NotImplemented";
        public const string LY_CODE = @"NotImplemented";
        public const string MA_CODE = @"NotImplemented";
        public const string MC_CODE = @"NotImplemented";
        public const string MD_CODE = @"NotImplemented";
        public const string ME_CODE = @"NotImplemented";
        public const string MG_CODE = @"NotImplemented";
        public const string MK_CODE = @"NotImplemented";
        public const string ML_CODE = @"NotImplemented";
        public const string MN_CODE = @"NotImplemented";
        public const string MO_CODE = @"NotImplemented";
        public const string MR_CODE = @"NotImplemented";
        public const string MT_CODE = @"NotImplemented";
        public const string MW_CODE = @"NotImplemented";
        public const string MX_CODE = @"NotImplemented";
        public const string MY_CODE = @"NotImplemented";
        public const string MZ_CODE = @"NotImplemented";
        public const string NA_CODE = @"NotImplemented";
        public const string NE_CODE = @"NotImplemented";
        public const string NG_CODE = @"NotImplemented";
        public const string NI_CODE = @"NotImplemented";
        public const string NL_CODE = @"NotImplemented";
        public const string NO_CODE = @"NotImplemented";
        public const string NZ_CODE = @"NotImplemented";
        public const string OA_CODE = @"NotImplemented";
        public const string OM_CODE = @"NotImplemented";
        public const string PA_CODE = @"NotImplemented";
        public const string PE_CODE = @"NotImplemented";
        public const string PG_CODE = @"NotImplemented";
        public const string PH_CODE = @"NotImplemented";
        public const string PL_CODE = @"NotImplemented";
        public const string PT_CODE = @"NotImplemented";
        public const string PY_CODE = @"NotImplemented";
        public const string QA_CODE = @"NotImplemented";
        public const string RO_CODE = @"NotImplemented";
        public const string RS_CODE = @"NotImplemented";
        public const string RU_CODE = @"NotImplemented";
        public const string RW_CODE = @"NotImplemented";
        public const string SA_CODE = @"NotImplemented";
        public const string SC_CODE = @"NotImplemented";
        public const string SD_CODE = @"NotImplemented";
        public const string SE_CODE = @"NotImplemented";
        public const string SG_CODE = @"NotImplemented";
        public const string SI_CODE = @"NotImplemented";
        public const string SK_CODE = @"NotImplemented";
        public const string SL_CODE = @"NotImplemented";
        public const string SM_CODE = @"NotImplemented";
        public const string SN_CODE = @"NotImplemented";
        public const string ST_CODE = @"NotImplemented";
        public const string SU_CODE = @"NotImplemented";
        public const string SV_CODE = @"NotImplemented";
        public const string SY_CODE = @"NotImplemented";
        public const string SZ_CODE = @"NotImplemented";
        public const string TD_CODE = @"NotImplemented";
        public const string TG_CODE = @"NotImplemented";
        public const string TH_CODE = @"NotImplemented";
        public const string TJ_CODE = @"NotImplemented";
        public const string TM_CODE = @"NotImplemented";
        public const string TN_CODE = @"NotImplemented";
        public const string TR_CODE = @"NotImplemented";
        public const string TT_CODE = @"NotImplemented";
        public const string TW_CODE = @"NotImplemented";
        public const string TZ_CODE = @"NotImplemented";
        public const string UA_CODE = @"NotImplemented";
        public const string UG_CODE = @"NotImplemented";
        public const string UY_CODE = @"NotImplemented";
        public const string UZ_CODE = @"NotImplemented";
        public const string VC_CODE = @"NotImplemented";
        public const string VE_CODE = @"NotImplemented";
        public const string VN_CODE = @"NotImplemented";
        public const string YU_CODE = @"NotImplemented";
        public const string ZA_CODE = @"NotImplemented";
        public const string ZM_CODE = @"NotImplemented";
        public const string ZW_CODE = @"NotImplemented";
    }
}
